name: Release metadata

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Setup NodeJS"
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Print GITHUB_EVENT
      run: |
        cat $GITHUB_EVENT_PATH

    - name: "Handle release event"
      run: python3 update_release.py

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update release metadata" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
